### ISSUE TITLE
[Server] Deck Controller / CRUD 기능 구현

### ISSUE THREAD

**Issue by jch422** [codestates/TFT-Guide#12]
### **ISSUE**

- Group: `server`
- Type: `feature`
- Detail: Deck 데이터에 대한 CRUD

### **TODO**

- [ ] `READ` Client로부터 전달받은 Deck id를 바탕으로 Deck 데이터를 조회하여 Client에 응답
- [ ]  `CREATE` Client로부터 전달받은 덱 정보를 DB에 저장
- [ ]  `UPDATE` Client로부터 전달받은 Deck id에 해당하는 Deck 데이터를 body로 전달된 데이터로 수정
- [ ]  `DELETE` Client로부터 전달받은 Deck id에 해당하는 Deck 데이터를 삭제

### **Labels**

- Estimated time: `E: 3h`
- Group : `server`
- Sprint: `Sprint2`
- Urgency: `High`
