### ISSUE TITLE
[Client] 메인 페이지 / 드래그 앤 드롭 구현

### ISSUE THREAD

**Issue by jch422** [codestates/TFT-Guide#3]
### **ISSUE**

- Group: `client`
- Type: `feature`
- Detail: 메인페이지에서 덱을 빌드하는 기능

### **TODO**

- [ ] 모든 champion pool을 담고 있는 컴포넌트 구현
- [ ] 유저가 빌드 중인 덱을 담고 있는 컴포넌트 구현
- [ ] 드래그 앤 드롭을 통하여 덱을 빌드 및 수정하는 기능 구현

### **Labels**

- Estimated time: `E: 6h`
- Group : `client`
- Sprint: `Sprint2`
- Urgency: `High`
