### ISSUE TITLE
[Client] 전적 검색 페이지 / 다른 유저의 전적 검색 기능 구현

### ISSUE THREAD

**Issue by jch422** [codestates/TFT-Guide#8]
### **ISSUE**

- Group: `client`
- Type: `feature`
- Detail: 다른 유저의 최근 전적을 검색

### **TODO**

- [ ] 소환사명을 입력할 수 있는 Input 컴포넌트를 구현한다
- [ ]  Riot games 에서 제공하는 API를 바탕으로 다른 유저의 최근 전적을 조회하는 기능을 구현한다
- [ ]  API 호출 후 응답받은 유저의 전적을 list 형태로 화면에 보여준다
- [ ]  스크롤링을 통해 전적을 추가적으로 로드한다.(Advanced)

### **Labels**

- Estimated time: `E: 6h(+3h)`
- Group : `client`
- Sprint: `Sprint2`
- Urgency: `High`
